# fly.toml app configuration file generated for gendaize-scheduler on 2023-05-30T17:12:05-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gendaize-scheduler"
primary_region = "mia"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0

[build]
  dockerfile = "Dockerfile"
